
base_local_planner: local_planner/LocalPlannerROS 

LocalPlannerROS:

  linear_vel_min: 0.0
  linear_vel_max: 1.0
  linear_vel_samples: 3

  angular_vel_max: 2.0
  angular_vel_samples: 3

  linear_acc_max: 1.0
  angular_acc_max: 2.0

  sim_time: 3.0
  sim_dt: 0.1

