
global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 3.0 
  publish_frequency: 0.0 
  static_map: false
  transform_tolerance: 0.5 

  origin_x: -50.0
  origin_y: -50.0
  width: 100.0
  height: 100.0

